### ISSUE TITLE
fail to clone 

### ISSUE THREAD

**Issue by sz-123** [computational-robotics-lab/comp-fab-a0#5]
when clone:
Submodule 'ext/eigen' (https://github.com/eigenteam/eigen-git-mirror) registered for path 'ext/eigen'
Submodule 'ext/nanovg' (https://github.com/memononen/nanovg) registered for path 'ext/nanovg'
Cloning into 'ext/eigen'...
fatal: unable to access 'https://github.com/eigenteam/eigen-git-mirror/': Failed to connect to 127.0.0.1 port 1080: Connection refused
fatal: clone of 'https://github.com/eigenteam/eigen-git-mirror' into submodule path 'ext/eigen' failed

**Comment by moritzge** [comment]
Did you configure a git proxy?

Maybe this helps: https://stackoverflow.com/questions/24543372/unable-to-connect-to-git-remote-repository

**Comment by sz-123** [comment]
It helps. Thank you!
